### ISSUE TITLE
using zotero translators without zotero

### ISSUE THREAD

**Issue by gideonite** [zotero/translators#1014]
Hi,

I'd like to use zotero translators to populate a bibtex file and a directory of pdfs. It'd be great if I could use the zotero browser plugin. Is this possible? Can someone point me to some code or documentation to get me started?

Thanks for the help,
Gideon.

**Comment by dstillman** [comment]
I'm not clear on your question — you say you want to use the translators without Zotero, but also that you want to use the browser plugin (i.e., Zotero)?

**Comment by gideonite** [comment]
Sorry, I was being unclear. I'd like to use emacs to access bibtex files directly which are created as output of translators and the browser plugin. Does that make more sense?

**Comment by adam3smith** [comment]
Since this really sounds like an application question -- how do I integrate Zotero into an emacs/bibtex workflow -- this is a much better question for the Zotero forums. You can look at the zotxt and better bibtex add-ons for Zotero which address various aspects of this, but then do follow up with their developers or on the forums.
