### ISSUE TITLE
WorldCat translator doesn't pull URL

### ISSUE THREAD

**Issue by owcz** [zotero/translators#1016]
This should be on the easier side, but the WorldCat translator doesn't add a URL (ideally in the `http://www.worldcat.org/oclc/933567313` format because some fields use active academic proxies, e.g., `http://www.worldcat.org.ezproxy.library.wisc.edu/oclc/933567313`)

**Comment by dstillman** [comment]
It's not supposed to. The URL field is for the canonical online source for an item. WorldCat is just a catalog.

**Comment by owcz** [comment]
By the same token, wouldn't HathiTrust be "just a catalog" too? If a user is saving a citation from WorldCat, they ostensibly want to refer back to that listing. As far as catalogs go, I'd wager that WorldCat is as canonical as catalogs get.

**Comment by dstillman** [comment]
> If a user is saving a citation from WorldCat, they ostensibly want to refer back to that listing.

I don't think that's a reasonable assumption at all. People save from WorldCat because it's a good source for metadata.

In any case, it doesn't have anything to do with how reputable or prominent WorldCat is as a database — WorldCat has no relation to the item in question and wouldn't be cited, so it doesn't belong in the URL field. A NYT article's URL goes in the URL field, because that's the canonical online source for the article and would be the URL that gets cited.

Translators have the option of creating attached links, and, e.g., the Amazon translator does that. But those create extra attachment items in people's libraries, and given that Zotero already has a built-in mechanism for doing a library lookup via WorldCat, it doesn't strike me as necessary here. (If we added an Amazon lookup engine, which we should probably do, we could stop attaching those links too.)

**Comment by dstillman** [comment]
(That said, switching to a lighter-weight mechanism for attached links, which don't really need to be full separate items, might be a good idea, and then we could be a bit more liberal about adding library catalog links. But UI clutter would still be a concern.)

**Comment by adam3smith** [comment]
One key factor here are citations: you would never want to include a URL to a library catalog in a regular citation style. You would, however, do so if you retrieved the full text of the book or article from that catalog, as you would with Hathi Trust.
That's the reason we don't include URLs for PubMed (the canonical source for article data in medical&bioscience research) but do so for PubMedCentral (which is basically the same thing but with article full texts).

**Comment by owcz** [comment]
WorldCat has been a poor metadata source in my experience

![screenshot 2016-02-07 08 08 19](https://cloud.githubusercontent.com/assets/778011/12873497/cc05fe88-cd83-11e5-89c6-34c0fa810779.png)

(HathiTrust fares slightly better, and that catalog translator also includes the URL, for what it's worth.) I would personally use URLs to WorldCat/HathiTrust in wiki citation style, but I can accept that I'm in the minority on that. Appreciate the responses.

Related to this—is there a reason why OCLC numbers aren't ingested, especially when a title doesn't have an ISBN? The wiki citation style has a dedicated parameter for OCLC, which could be an alternative to needing the WorldCat direct URL.

**Comment by adam3smith** [comment]
Yes, Wikipedia citations maybe unusual in that respect, that's why I specified "regular" citation style.

As for data quality, I'm not aware of a good way to get high quality metadata out of Worldcat. We grab their RIS currently, but it's not like they provide anything good via any of their APIs. I think this gets lost during aggregating data from different libraries. @zuphilip probably knows a bit more on this.

As for OCLC Numbers -- we just don't have a place to put it and I'm not sure we should have (actually not sure; not saying we definitely shouldn't).

**Comment by zuphilip** [comment]
I think OCLC is not providing the MARC data on the website based on some (strange) management decision. For the API one needs a key and I guess there are more restrictions for usage. See also this [recent discussion on twitter](https://twitter.com/lukask/status/694122705977737216).

BUT, I think it is worth have the possibilities to save every identifier, like PMID, ISBN, OCLC numbers, .... On a general viewpoint we can allow every URI which describes the same object and can therefore be linked with `owl:sameAs` in the semantic web.

**Comment by adam3smith** [comment]
yeah, good point on the IDs, though it's a datamodel&GUI challenge

**Comment by owcz** [comment]
The OCLC ID parameter would be useful for my citations. Where should I take this discussion? zotero/zotero/issues? Does it need to have consensus elsewhere (like the forums) first?

Re: the original point, it looks like the best answer is to use another source for book metadata—perhaps Google Books or HathiTrust

**Comment by adam3smith** [comment]
Google Books is even worse, on average. I'd recommend using library of congress whenever they have a record. That's what we do for our ISBN retrieval. 

I suppose Zotero forums is the best place for OCLC discussion, though I think @zuphilip is right that the correct way to think about this is not about OCLC in particular, but with a broader approach to IDs (PMID, PMCID, arxivID and many more).

**Comment by owcz** [comment]
https://forums.zotero.org/discussion/56659/a-broader-approach-to-ids-oclc-pmid-pmcid-arxivid/
