### ISSUE TITLE
TEI Output Bug: For Item Type "Book Section" the Book Title is not output

### ISSUE THREAD

**Issue by acmuller** [zotero/translators#1040]
When we do Export Item in TEI, in the case of Item Type "Book Section", the "Book Title" field comes out as an empty node.

**Comment by adam3smith** [comment]
is this a recent regression or has this been the case for longer?

**Comment by acmuller** [comment]
It seems to be recent. In fact, it seems to have begun with the previous recent fix.

**Comment by FranziskaHorn** [comment]
Unfortunately, the same happens if you export a conference paper. I think it would help to add explicit statements to export the book title and the proceedings title - although these changes don't refer to the previous fix. Currently, only the field `item.publicationTitle` is exported:

```
        // there should be a publication title!
        if(item.publicationTitle){
            var pubTitle = teiDoc.createElementNS(ns.tei, "title");
            if(item.itemType == "journalArticle"){
                pubTitle.setAttribute("level", "j");
            }
            else{
                pubTitle.setAttribute("level", "m");
            }
            pubTitle.appendChild(teiDoc.createTextNode(replaceFormatting(item.publicationTitle)));
            monogr.appendChild(pubTitle);
        }
```

But fields for book sections and conference papers are named differently: `item.bookTitle` and 
`item.proceedingsTitle`. If the translator contains additional rules for these item types after line 216, the export should work correctly again. (At least it worked as I tested it with a group library in Zotero Standalone.)

```
        // book title
        if(item.bookTitle){
	    var bookTitle = teiDoc.createElementNS(ns.tei, "title");
            bookTitle.setAttribute("level", "m");
            bookTitle.appendChild(teiDoc.createTextNode(replaceFormatting(item.bookTitle)));
            monogr.appendChild(bookTitle);
        }
		
	// proceedings title
        if(item.proceedingsTitle){
	    var proTitle = teiDoc.createElementNS(ns.tei, "title");
            proTitle.setAttribute("level", "m");
            proTitle.appendChild(teiDoc.createTextNode(replaceFormatting(item.proceedingsTitle)));
            monogr.appendChild(proTitle);
         } 
```


I think it is also necessary to remove these lines:


```
// nonetheless if the user pleases this has to be possible
else if(!item.conferenceName){
    var pubTitle = teiDoc.createElementNS(ns.tei, "title");
    pubTitle.setAttribute("level", "m");
    monogr.appendChild(pubTitle);
}
```


If I understand the code correctly there is no statement to export something, e.g. `pubTitle.appendChild(teiDoc.createTextNode(replaceFormatting(item.publicationTitle)));`
Maybe this code snipped is the reason for the empty elements `<title level="m"/>`.

**Comment by FranziskaHorn** [comment]
Unfortunately, the new output contains book title and proceedings title twice if I export via API request:

```
<monogr>
	<title level="m">Proceedings of the 21st International Congress of Onomastic Sciences. [...]</title>
	<title level="m">Proceedings of the 21st International Congress of Onomastic Sciences. [...]</title>
[...]	
</monogr>
```

The problem does not occur if I export items in Zotero Standalone.

The translator has two single statements to export the book title and the proceedings title: 
```
        // book title
        if(item.bookTitle){
        var bookTitle = teiDoc.createElementNS(ns.tei, "title");
            bookTitle.setAttribute("level", "m");
            bookTitle.appendChild(teiDoc.createTextNode(replaceFormatting(item.bookTitle)));
            monogr.appendChild(bookTitle);
        }

	// proceedings title
        if(item.proceedingsTitle){
        var proTitle = teiDoc.createElementNS(ns.tei, "title");
            proTitle.setAttribute("level", "m");
            proTitle.appendChild(teiDoc.createTextNode(replaceFormatting(item.proceedingsTitle)));
            monogr.appendChild(proTitle);
         } 
```

It seems that both item types have an additional field `publicationTitle` but the JSON output doesn't show the field. The field `publicationTitle` is exported here:
        
```
	if(item.publicationTitle){
            var pubTitle = teiDoc.createElementNS(ns.tei, "title");
            if(item.itemType == "journalArticle"){
                pubTitle.setAttribute("level", "j");
            }
            else{
                pubTitle.setAttribute("level", "m");
            }
            pubTitle.appendChild(teiDoc.createTextNode(replaceFormatting(item.publicationTitle)));
            monogr.appendChild(pubTitle);
        }
```

In consequence, the output via api request contains two instead of one element `<title level="m">`.
I think it would help to add an additional conditions for these item types in line 210, the export should work correctly again.
```

	if(item.publicationTitle && (item.itemType != "bookSection" && item.itemType != "conferencePaper")){
	    var pubTitle = teiDoc.createElementNS(ns.tei, "title");
            if(item.itemType == "journalArticle"){
                pubTitle.setAttribute("level", "j");
            }
            else{
                pubTitle.setAttribute("level", "m");
            }
            pubTitle.appendChild(teiDoc.createTextNode(replaceFormatting(item.publicationTitle)));
            monogr.appendChild(pubTitle);
        }
```

**Comment by adam3smith** [comment]
yes, that makes sense. Publication title is a  catchall name for those others. I'm actually surprised this doesn't also produce duplicate fields in Zotero Standalone. Without looking at the code, wouldn't `if`  -- `else if`  -- `else if` make more sense than that massive `if` you propose?

**Comment by FranziskaHorn** [comment]
Do you mean this if statement:
`if(item.publicationTitle && (item.itemType != "bookSection" && item.itemType != "conferencePaper"))` ?

From my point of view there is no possibility to reduce the statement because there shouldn't be an export of the field `item.publicationTitle` for the item types `bookSection` and `conferencePaper`.

It would be an alternative if publication title is no longer a catchall name for other item types. I think it is a disadvantage that publication title only works as catchall name for exports via API requests and not in Zotero Standalone.

**Comment by adam3smith** [comment]
```
if (item.bookTitle){...}
else if (item.proceedingsTitle) {...}
else if (item.publicationTitle) {...}
```

or what am I missing?

**Comment by FranziskaHorn** [comment]
I didn't thought about that. I tested it, the export in Zotero Standalone works correctly. 
My only conern is that still the publication title will be exported additionally via API request for bookSection and conferencePaper. But if that isn't the case this solution is much briefer than the one before:

```
        // book title
        if (item.bookTitle){
    	 var bookTitle = teiDoc.createElementNS(ns.tei, "title");
            bookTitle.setAttribute("level", "m");
            bookTitle.appendChild(teiDoc.createTextNode(replaceFormatting(item.bookTitle)));
            monogr.appendChild(bookTitle);
        }
        // proceedings title
        else if(item.proceedingsTitle) {
            var proTitle = teiDoc.createElementNS(ns.tei, "title");
            proTitle.setAttribute("level", "m");
            proTitle.appendChild(teiDoc.createTextNode(replaceFormatting(item.proceedingsTitle)));
            monogr.appendChild(proTitle);
        }
        // other publication titles
        else if(item.publicationTitle) {
            var pubTitle = teiDoc.createElementNS(ns.tei, "title");
            if(item.itemType == "journalArticle"){
                pubTitle.setAttribute("level", "j");
            }
            else{
                pubTitle.setAttribute("level", "m");
            }
            pubTitle.appendChild(teiDoc.createTextNode(replaceFormatting(item.publicationTitle)));
            monogr.appendChild(pubTitle);
        }
```

**Comment by adam3smith** [comment]
pretty sure it wouldn't, because of the `else if` Unfortunately I don't think we can test this easily without actually making the change.

**Comment by FranziskaHorn** [comment]
Allright, can you make the change directly or is it better to make a pull request?

**Comment by adam3smith** [comment]
PR is going to be faster; it'll take me a bit until I get to this.

**Comment by adam3smith** [comment]
fixed in

**Comment by FranziskaHorn** [comment]
Thank you very much, now the export for bookSection and conferencePaper via API request works correctly!

**Comment by adam3smith** [comment]
whew. Sorry for the many turns this took.
