### ISSUE TITLE
Openreview.net

### ISSUE THREAD

**Issue by black-puppydog** [zotero/translators#1188]
There's no translator, and it would be cool if there was.
This is used for submissions in review (surprise!) so there's no .bib files or thelike.

Example: https://openreview.net/forum?id=SJ8BZTjeg

**Comment by zuphilip** [comment]
@black-puppydog Do you have any contact to the people behind this website? Maybe we can convince them to include some metadata (e.g. highwire tags) which might also increase their visibility on GoogleScholar etc. Otherwise it might be unlikely that someone (if not you) will create a specific translator for that page.

**Comment by owcz** [comment]
I sent a message at https://openreview.net/contact referring them here

**Comment by black-puppydog** [comment]
I just tested that, and it seems that the openreview team really liked the idea. works for me, can anyone confirm? :)

**Comment by zuphilip** [comment]
Yes, I see some metadata in HighWire tags which will be recognized by Zotero including the link to the PDF.

**Comment by black-puppydog** [comment]
so can this be considered closed then? or is something missing? Like I said: it works for me. :stuck_out_tongue:

**Comment by zuphilip** [comment]
Yeah, I think you can close this issue then.
