### ISSUE TITLE
Fake <meta name="author"> tags

### ISSUE THREAD

**Issue by zhaofengli** [zotero/translators#1194]
There is a fake `<meta name="author">` tag on http://www.discoverireland.ie/Arts-Culture-Heritage/dunleckney-manor/11131

```
<meta name="author" content="Website design and development by Tibus" />
```

Some heuristics may be needed for cases like this.

**Comment by adam3smith** [comment]
I don't think we'll be able to handle those cases. The name="author" tag is fairly low down in our list of tags we're using for author import exactly because of this, but I don't think I want to try to write and maintain the code that distinguishes something like this from an organizational name or a complex firstname -- particles -- lastname
