### ISSUE TITLE
Translator "Springer Link.js" returns incorrect type for a link 

### ISSUE THREAD

**Issue by sonali0901** [zotero/translators#1245]
I tried to test Springer Link.js translator in scaffold for the link https://link.springer.com/chapter/10.1007/11926078_68 . The detectWeb returned type "conferencePaper" when it should have returned "bookSection" since it is a chapter of a book.
A piece of code added at line 39
```
case "protocol":
     if (ZU.xpathText(doc, '//meta[@name="citation_conference_title"]/@content')) {
				return "conferencePaper";
				break;
			} else {
				return "bookSection";
				break;
			}
```
is causing this. Previously, the code for this case was as follows:
```
		case "protocol":
			return "bookSection";
			break;
```
This link is a test link for citoid testing and hence citoid tests are failing when we are trying to update our fork from this repo's upstream. Also, in the first test case of this translator, the itemType for the url http://link.springer.com/chapter/10.1007/978-3-540-88682-2_1 has been changed to conferencePaper from bookSection. Is this intentional and correct? I am learning to write Zotero translators.

**Comment by zuphilip** [comment]
Both examples are papers presented at a conference are better handled as `conferencePaper` in Zotero translators rather than `bookSection`, because this is more appropriate here and there are better subfields available. Springer recently helped us to make this possible https://github.com/zotero/translators/pull/1192, by assigning information (again) in `<meta>` fields of their pages https://github.com/zotero/translators/issues/1187. I suggest you change your test cases in Citoid accordingly.

**Comment by sonali0901** [comment]
@zuphilip  Thanks for explaining this. Makes sense.
