### ISSUE TITLE
Online Translator Tests are currently not working

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#1356]
The [online translator tests](https://zotero-translator-tests.s3.amazonaws.com/index.html) are currently not working. As far as I can say this started after @dstillman worked on the translation-server and switched the tests from 4.0 to 5.0.

What are the further plans for the online translator tests? When will they work again?

**Comment by dstillman** [comment]
Sorry, should be running again now (using current translation-server HEAD, not the 4.0 version in Docker Hub). Various things ([like import translators](https://github.com/zotero/translation-server/issues/49)) are still broken in the 5.0 version.

Also it looks like a lot of tests are broken due to data format changes in 5.0, most notably with tags. I'm not totally sure what the situation is there. It looks like tests generally expect just an array of strings, presumably because all tags from translators have traditionally been automatic tags, but the 5.0 code is producing a `{ tag: "foo" }` object. That might make sense if it was to allow translators like Zotero RDF to create manual tags and the rest to create automatic (`type: 1`) tags, but it's not actually producing `type: 1` tags (and it would be kind of tedious anyway, since manual tags from translators would be the rare exception), so I'll [look into this](https://github.com/zotero/zotero/issues/1254).

**Comment by dstillman** [comment]
Tests are up again, on a new domain, and in a more stable fashion based on translation-server v2: https://translator-tests.zotero.org

As a reminder, translation-server doesn't run JavaScript, even for the initial page load, unlike the Connector, which uses XHR for subsequent requests but starts with the initial JS-rendered page, so various sites (like, say, zotero.org) won't work. We could consider fixing that, but we can discuss that elsewhere.
