### ISSUE TITLE
BibLaTeX import

### ISSUE THREAD

**Issue by twsh** [zotero/translators#1400]
There is a BibLaTeX export translator, and a BibTeX import/export translator. This means that if one imports a BibLaTeX file BibLaTeX field names are ignored. For example, the correct way to give the title of the journal for an article in BibLaTeX is 'journaltitle', rather than 'journal'. This won't be mapped to publication by Zotero. Both translators target .bib extensions, so it's not clear that just adding import to BibLaTeX.js would be the right thing to do. One idea that occurred to me would be to add some common BibLaTeX field names to the BibTeX translator. But then it wouldn't really be a BibTeX translator any more. Another option would be to have two exports and one unified import.

Does anybody have any suggestions about this? I think I will try to get something working for my own interest.

**Comment by adam3smith** [comment]
sorry this never received an answer -- I don't think it would be hard to simply allow biblatex fields on import in the regular bibtex.js translator. This should be clearly marked in the code for readability, but otherwise, as long as they have different names, I don't think that'll cause any issues. 

IIRC there are a couple of fields that actually have different meanings in bibtex and biblatex -- we'd probably want to find a good heuristic (based on other fields present such as e.g. the dat format) to decide what to do for those fields. 

We haven't gotten a lot of requests for biblatex import so this isn't high priority for me, but I'd be very happy to take and review pull requests.
