### ISSUE TITLE
Reevaluate use of GBV for ISBN lookups

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#1407]
I don't have any real data to go on, but testing Add Item by Identifier with 9781479347711, I noticed that it's using GBV, which returns a weird, mangled title (seemingly entered by hand by a non-native English speaker?), as well as tags in German and "Gemeinsamer Bibliotheksverbund ISBN" showing in the Library Catalog field. Needless to say, this is not a good experience, particularly for non-German users.

GBV:

```
{
    "itemType": "book"
    "place": "Lexington, KY"
    "publisher": "CreateSpace"
    "ISBN": "978-1-4793-4771-1"
    "date": "2013"
    "extra": "OCLC: 935065868"
    "libraryCatalog": "Gemeinsamer Bibliotheksverbund ISBN"
    "language": "eng"
    "title": "Citations out of box: [adapting Zotero for legal and multilingual research ; v 1.0]"
    "shortTitle": "Citations out of box"
    "numPages": "137"
    "creators": [
        "0": {
            "firstName": "Frank G."
            "lastName": "Bennett"
            "creatorType": "author"
        }
    ]
    "tags": [
        "0": {
            "tag": "Literaturverwaltung"
            "type": 1
        }
        "1": {
            "tag": "Mehrsprachigkeit"
            "type": 1
        }
        "2": {
            "tag": "Rechtswissenschaft"
            "type": 1
        }
    ]
}
```

WorldCat:

```
{
    "itemType": "book"
    "place": "S.l."
    "publisher": "Frank G. Bennett"
    "ISBN": "978-1-4793-4771-1"
    "date": "2013"
    "extra": "OCLC: 851554430"
    "libraryCatalog": "Open WorldCat"
    "language": "English"
    "title": "Citations, out of the box: adapting Zotero for legal and multilingual research"
    "shortTitle": "Citations, out of the box"
    "creators": [
        "0": {
            "firstName": "Frank G"
            "lastName": "Bennett"
            "creatorType": "author"
        }
    ]
    "tags": []
}
```

When the GBV translator was first added, there was [some talk](https://github.com/zotero/translators/issues/846) of choosing the priority more intelligently based on the source of the book (based on ISBN ranges). Is that something we can do? Can we limit use of GBV to German sources?

Regardless, when we do use GBV, we need to strip the German tags for non-German sources.

/cc @zuphilip, who added the GBV translator originally

**Comment by zuphilip** [comment]
What is the motivation for this suggestion? Is it only about the data quality or do you have anything else in mind (e.g. performance issues)? Actually, I would rather expect to add more ISBN translators e.g. for Chinese, Japenese or Arabic books, then to delete some of them.

About the title:
```
"title": "Citations out of box: [adapting Zotero for legal and multilingual research ; v 1.0]"
```
The title misses the comma after the `citations` and puts the subtitle into a square bracket and puts also the `v 1.0` there. I think the square bracket indicate that they took this information from the front cover rather than the "Haupttitelseite". The version number is also part of the front cover and are entered as well as extra to the title (this seems IMO not very useful). 

<details>
"Zusätze zum Sachtitel, die nicht auf dem Haupttitelblatt stehen, werden mit eckigen Klammern übernommen, wenn das zum Verständnis erforderlich erscheint (§ 134, 3)." http://www.payer.de/rakwb/rakwb01.htm (Angabe der Zusätze zum Sachtitel)

</details>

In summary there are some rules how librarians are entering the title information. However, lately Germany, Switzerland and Austria switched to the international cataloguing rules RDA, which are also used by the US libraries. Thus, at least in theory, they should in the future extract the title information the same. For practice I just tried to ask my colleagues: https://twitter.com/zuphilip/status/906824259749793794

On the other hand I see in your example, that WorldCat misses the information about the publisher, the place of publication `S. l.` = sine loco = without a place, number of pages is missing, the language is not in any standard form. Moreover, this is an easy book compared to dissertations, conference proceedings, books in a serie etc.

Personally, I don't care much about the tags. But I have a lot of German as well as English tags in my library. Maybe we can say, when I visit a website in any language, then I also accept to add the tags in that language. But for search translators this could be more unexpected.

We can
* Delete the tags in all ISBN search translators
* Delete the brackets around the subtitle in the MARC translator. [There is already some mechanism for that in place](https://github.com/zotero/translators/blob/master/MARC.js#L45-L48), such that we only have to apply it as well to the subfield which contains the subtitle.
* Ask the GBV for correcting the title for this entry (add the comma)
* Analyze further about the subtitle or title extras in GBV. Maybe some patterns can be derived from there.

**Comment by zuphilip** [comment]
> When the GBV translator was first added, there was some talk of choosing the priority more intelligently based on the source of the book (based on ISBN ranges). Is that something we can do? Can we limit use of GBV to German sources?

The ISBNs have some [language/country code](https://de.wikipedia.org/wiki/ISBN-Gruppennummer) depending on the place of publication:
* 978-0-... and 978-1-... is for English speaking countries
* 978-3-.... is for German speaking countries
etc.

However, large publishers are producing books in many languages and have different places of publications...

**Comment by dstillman** [comment]
The book's title is "Citations, out of the box" — note the "the". "out of box" seems like a mistake by a non-native English speaker. Again, I don't have any data here, but given this example, I'm skeptical that we should be prioritizing GBV for non-German titles — a mangled, ungrammatical title is worse than missing fields.

**Comment by zuphilip** [comment]
Ah, okay the `the` is also missing. But I would say these are oversights (Flüchtigkeitsfehler) and I doubt that this has anything to do with native vs. non-native speakers. But I have as well no data to base this claim on. Maybe, we can think about some set for testing the quality to have data we can try to analyze?

**Comment by zuphilip** [comment]
Please note also that by priority numbers the first catalogue to check for every ISBN search is the library of congress. Thus, I guess that the number of books not in the library of congress but in any German library is a very few fraction in total.

**Comment by adam3smith** [comment]
Yeah, with the tags stripped once #1418 is merged, and given that most English titles will be represented in LoC (and Open Worldcat having a whole host of its own issues, e.g. https://forums.zotero.org/discussion/comment/286301 ), I think we should just leave this as is. For rare titles, both WorldCat and GBV will suffer from occasional glitches in cataloging by individual librarians such as this one, but in addition to that, WorldCat suffers from incomplete RIS vs. GBV's proper MARC. 
So if @dstillman is OK with that, I'd close this once the tag (and square brackets) issue are addressed.

**Comment by dstillman** [comment]
All right — thanks for the GBV improvements.

**Comment by zuphilip** [comment]
( FYI, the GBV entry for this book is now corrected: http://opac.tib.eu/DB=4.1/XMLPRS=N/PPN?PPN=751750891 🐝 )
