### ISSUE TITLE
AMS MathSciNet -- Target needs update

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1451]
According to report https://forums.zotero.org/discussion/68245/ams-mathscinet-broken#latest
all that's needed is switching www. --> mathscinet. in target, though haven't checked

**Comment by gjankowiak** [comment]
I (initial reporter) just want to mention that I'm not familiar with how Zotero works, I tried unpacking/modifying/repacking zotero.jar, with no effects. I basically replaced all occurences of www. with mathscinet., since I don't know how the zotero/firefox/zotero-connector ecosystem works, this might make no sense.

After that I roll-backed my changes and modified `.mozilla/firefox/XXX.default/browser-extension-data/zotero@chnm.gmu.edu/storage.js` which is significantly more simple and has only one occurence of the mathscinet url, and this seemed to do the trick.

**Comment by adam3smith** [comment]
The translators are simple, individual .js files in the translators directory in the Zotero data folder: https://www.zotero.org/support/zotero_data you can change them on the fly and won't need any repacking. The relevant line is the taget at the top.
(In the case of changing targets, you'll need to restart Zotero and browser after making that change) 
I wouldn't touch any of the other components of Zotero in a system you're using for work.

**Comment by gjankowiak** [comment]
Thank you for the explaination! I've just filed a pull requests for thoses changes. I updated also the subdomain in the code, since I guess the redirects won't be active forever.
