### ISSUE TITLE
IEEE doesn't import PDFs from PDF view and multiples

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1469]
Examples: http://ieeexplore.ieee.org/xpl/mostRecentIssue.jsp?reload=true&punumber=7866667 (multiple; also affects regular search results)

PDF view: 
http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8022881

Reported: 
https://forums.zotero.org/discussion/68572/chrome-connector-cannot-automatically-batch-import-from-ieee-xplore-with-pdf#latest

https://forums.zotero.org/discussion/68563/it-can-not-download-the-pdfs-automatically-report-id-1050855996#latest

**Comment by zuphilip** [comment]
The first [line of the IEEE Xplorre translator](https://github.com/zotero/translators/blob/master/IEEE%20Xplore.js#L16) is problematic for Scaffold:
```js
if(doc.defaultView !== doc.defaultView.top) return;
```
I don't know what this does and if we still need it... CC @dstillman 

---

However, the problems reported for multiples and pdf view are IMO related to the recent changes in how to load documents, because the pages is relying heavingly on AJAX calls, e.g.
```html
<li class="large doc-actions-item" ng-class="{'disabled-look': !ft.article.fullTextAccess || ft.article.isACM}">
	<!-- ngIf: ::!ft.article.fullTextAccess && ft.article.canAddToFileCabinet -->
	<!-- ngIf: ft.article.fullTextAccess -->
	<a class="doc-actions-link stats-document-lh-action-downloadPdf_2 ng-scope" ng-href="/stamp/stamp.jsp?arnumber=7870240" ng-if="ft.article.fullTextAccess" href="/stamp/stamp.jsp?arnumber=7870240">
	<i class="icon doc-act-icon-pdf"></i> Download PDF
	</a><!-- end ngIf: ft.article.fullTextAccess -->
	<!-- TODO: Check if this needs SIP directive because it might just be disabled and not clickable -->
	<!-- ngIf: ::!ft.article.fullTextAccess && !ft.article.canAddToFileCabinet -->
</li>
```
Any ideas how to circumevent this? The actual pdf url looks easy to build without this a-tag, but then we don't know whether the user have licensed to content and the link will work in the end or not.

**Comment by adam3smith** [comment]
I'm going to close this issue as I can no longer replicate it.

**Comment by zuphilip** [comment]
Are the PDFs now saving correctly? If yes, then we can also close my PR #1631.

**Comment by adam3smith** [comment]
Definitely saving for me. I'd like for someone else to confirm, btu then yes, we can close the PR (and I think there is one more ticket)
