### ISSUE TITLE
Should the Zenodo translator extract "Available in" or "Indexed in" links as URL?

### ISSUE THREAD

**Issue by katrinleinweber** [zotero/translators#1517]
Hello @zuphilip and @adam3smith! 1st off: Happy New Year :-)

I have an FR or discussion point about [Zenodo.js](https://github.com/zotero/translators/blob/master/Zenodo.js): Because a) Zenodo-DOIs resolve to a Zenodo "record" URL , and b) the translator extracts the DOI just fine, should it maybe refrain from importing the "record" URLs as URLs of the Zotero entries? It's kind of a duplicate, right?

How about instead extracting the `href` around `img` of `class="img-thumbnail"`? That would be the URL the authors of the Zenodo record choose for themselves. Here's an example: https://zenodo.org/record/266799

```
<div class="well metadata">
  
    <small class="text-muted">Indexed in</small>
    <a href="https://www.openaire.eu/search/publication?articleId=od______2659::fc5228fc37e2da95e11fc14743100ba8">
      <img src="/static/img/openaire-horizontal-old.png" class="img-thumbnail" width="100%" />
    </a>
</div>
```

The `https://www.openaire.eu/search/publication?articleId=...` would be the URL I mean.

For Zotero users, this proposed change would provide the benefit of enriching the metadata they import from Zenodo: 2 URLs instead of 1 :-)

PS: Zenodo records that were generated from a GitHub repo also contain a ["Supplement to:"](https://github.com/zenodo/zenodo/search?utf8=%E2%9C%93&q=%22Supplement+to%22&type=) URL with also links to the repo. Maybe that could be used as well.

**Comment by zuphilip** [comment]
The `url` field as well as the `doi` are mainly for citation purposes. Thus, the question is, which url would we need in a citation of this document, or wouldn't we need any url. I don't think anyone would use the url from OpenAIRE in a citation. Actually, Zenodo mentions them as an "Indexer", which is negligable for citation purposes. It would be possible to save a link as an attachment, but I don't see any benefit here.

My suggestions here: Either leave it as it is, or delete the url field always an leave it blank, because we already have the doi.

**Comment by adam3smith** [comment]
we save the URL for resources by default and that makes sense (e.g. to track where something was actually downloaded from: some articles have different sources than the authoritative one the DOI points to). Citation styles don't care -- most styles will explicitly prefer DOI over URL, so this shouldn't really show up. I don't really see the need to change anything here.

**Comment by katrinleinweber** [comment]
I'm probably the minority here in [preferring to have each hyperlinked by respective parts of a citation](https://github.com/KonScience/Citation-Style#citation-style-for-science-podcasts).

However, adjusting the URL in this case would also provide a bit of convenience for Zotero users (the app, not readers of a bibliography) in that they can (if needed) visit the source directly, a bit faster, and with fewer clicks, because both DOI.org and Zenodo.org would be bypassed.

**Comment by adam3smith** [comment]
Sorry, I don't think we'll do this. I think the added benefit is small and more importantly placing a URL from a different site in the URL field will cause confusion. 

The github issue is a bit different, because there arguably the github repo is the "real" resource, so we could look at that one more closely.

**Comment by katrinleinweber** [comment]
Isn't this only confusing to users who believe that Zenodo is _the_ primary source? It is not, whenever it refers to the original itself, and in these cases, users might even be confused in a productive way, because  they are lead to better understand Zenodo's role.
