### ISSUE TITLE
Add support for NBER pdf pages

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#1592]
e.g.  http://www.nber.org/papers/w17577.pdf

This is just the landing page + .pdf, should be easy

**Comment by AbeJellinek** [comment]
>This is just the landing page + .pdf

is no longer true, unfortunately, since it now redirects to a slightly more complex PDF URL. Few translators detect PDFs; is there a reason why this one in particular should?

**Comment by dstillman** [comment]
> Few translators detect PDFs; is there a reason why this one in particular should?

It's something we like to do when it's easy. We obviously tell people who make it to the documentation or forums to click back and save from the abstract page, but lots of people just try to save while viewing the PDF. When we can easily detect and save based on the PDF URL, we should, instead of falling back to metadata retrieval.
