### ISSUE TITLE
APA PsycNET fails in Firefox

### ISSUE THREAD

**Issue by tomellor** [zotero/translators#1655]
- APA PsycNET fails in Firefox 59 on Fedora 27 and Firefox 59 Windows 10.
- APA PsycNET works in Chrome 66 on Windows 10, Chrome 66 on Fedora 27, and Chromium 65 on Fedora 27.
- All tests done in bare profiles, no configuration changes or add-ons besides Zotero Connector

POST request to '/api/request/record.exportRISFile' in function scrape() responds with 500 in Firefox and with 200 in Chrome. Some headers differ between browsers, and in testing I found that the POST from Firefox does not include the Referer header but if it is edited and resent to include Referer then the response will be 200. Example POST from Firefox below:

`Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 119
Content-Type: application/json
Cookie: ...
Host: psycnet.apa.org
Pragma: no-cache
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0`

Should respond with 500 but if we edit and resend the POST while including `Referer: http://psycnet.apa.org/record/2018-07710-001` then the response will be 200. Evidently a Referer header is required for the API at http://psycnet.apa.org/api/request/record.exportRISFile

Not sure how to fix this situation as APA PsycNET does explicitly provide the Referer header already. I've read https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name which indicates some headers including Referer "cannot be modified programmatically". Also https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy indicates that in most contexts (outside of pages delivered over HTTPS linking to same-origin pages also delivered over HTTPS), the Referer header will be excluded.

**Comment by dstillman** [comment]
Thanks for debugging this. Should be fixed in the latest <a href="https://www.zotero.org/support/dev_builds#zotero_connector">Zotero Connector beta</a>. Explanation <a href="https://github.com/zotero/zotero-connectors/commit/17a54775183bc4a533cd47c8f6d33cc8c1ba3ea3#diff-2bd5f69384a30c802c44a6d01eef4bdbR80">here</a>.

**Comment by dstillman** [comment]
The icon is still very buggy (and sometimes nonfunctional) for me in Firefox, but we'll see if we can do anything to improve that in https://github.com/zotero/zotero-connectors/issues/251.

**Comment by dstillman** [comment]
Oh, also, the Referer assignment can be removed from the translator, since it has no effect anyway (other than logging an error). That might have worked in Zotero 4.0 for Firefox, but it doesn't work these days (even for the privileged XHR that Firefox content scripts were using before this patch). The request just gets the page's URL set as the Referer.

**Comment by zuphilip** [comment]
Thank you @tomellor for the description and analysis of the problem with firefox and thank you @dstillman for the fix in the latest beta of the connector! I hope that also the buggy icon can be improved. CC @bwiernik

**Comment by bwiernik** [comment]
Awesome! My students will be very happy.

**Comment by tomellor** [comment]
Ah interesting. Glad I didn't try to find the solution myself, you were on top of it!
