### ISSUE TITLE
ACL Anthology translator enhancement

### ISSUE THREAD

**Issue by nschneid** [zotero/translators#1734]
@GuyAglionby, thanks for your work on #1707—the new BibTeX-based translator is working great!

I'm wondering if it would be possible to add an enhancement, namely populating the Conference Name field with the abbreviated name of the conference—"ACL 2018", "COLING 2018", "NAACL-HLT 2018", etc.—for main conference papers only (excluding regular and student research workshops, demos, and tutorials). Currently I fill this field in manually so my medium-form and short-form [custom exporters](https://gist.github.com/nschneid/2257875) will display that instead of the spelled-out name.

I assume this would require the code to contain a list of the standard conference abbreviations (as seen on the Anthology [homepage](https://aclanthology.coli.uni-saarland.de/)), and correctly discern hyphenated conferences like "ACL-IJCNLP" from the proceedings title. As the proceedings titles are formulaic, I think this could be accomplished with a few regexes.

**Comment by GuyAglionby** [comment]
This seems like a good addition to me. Helpfully, each event has a unique letter code as seen in the URLs and PDF titles for each paper (e.g. ACL is P, NAACL is N, COLING is C) which have been stable over the years and so could be hardcoded in. Otherwise as you say we could regex on BibTeX `booktitle`, but this seems a little more complicated. Keen for feedback before I go ahead and implement this. Thanks!

**Comment by nschneid** [comment]
The letter code may help, but note that tutorials, demos, and student research workshop papers are typically listed with the same letter as the main conference papers. The letter doesn't indicate which years are plain ACL and which are ACL-IJCNLP (for example), and *SEM and SemEval fall under the same letter but are cited differently. So I think some processing of the booktitle is necessary.

**Comment by GuyAglionby** [comment]
Good point, thanks for the heads up. It looks like we can use the venue information on each page as well, as it correctly encodes single as well as joint conferences (e.g. [ACL-IJCNLP 2015](https://aclanthology.coli.uni-saarland.de/papers/P15-1000/p15-1000), [NAACL-HLT 2016](https://aclanthology.coli.uni-saarland.de/papers/N16-1000/n16-1000), [EMNLP-CoNLL 2012](https://aclanthology.coli.uni-saarland.de/papers/D12-1000/d12-1000), [ACL-HLT 2008](https://aclanthology.coli.uni-saarland.de/papers/P08-1000/p08-1000)). I'm not sure of the correct notation for workshops -- would "WS-CMCL 2018" be appropriate [here](https://aclanthology.coli.uni-saarland.de/papers/W18-0100/w18-0100) (and indeed, should we include the year or leave that to the date field)? 

The only example not following this pattern that I can find is [NAACL-HLT 2018](https://aclanthology.coli.uni-saarland.de/papers/N18-1000/n18-1000), but given that they do follow this for all other NAACL-HLT I suspect this is an error. I've submitted a ticket [here](https://github.com/acl-org/acl-anthology/issues/80) about this. Otherwise I think this approach should work without having to have a load of regexes. Let me know what you think!

**Comment by nschneid** [comment]
Ah, good, it looks like that should work for hyphenated venues.

"*SEMEVAL" is treated as a single venue, but in citations it is either *SEM or SemEval, so this presumably needs to be handled based on the proceedings title. And tutorials, demos, etc. need to be filtered out based on the proceedings title.

I avoid using abbreviations for workshops (workshops are not as standardized from year to year), so I would not fill the conference name field for anything with "WS" as a venue.

**Comment by knmnyn** [comment]
@nschneid Yes, we use *SEMEVAL to denote both *SEM and SemEval, but this is not optimal either.  Both parties wanted visibility on the home page, so we listed them together this way for the current timeframe.  We could potentially fix this if there is good impetus for doing so.

**Comment by nschneid** [comment]
@GuyAglionby, what is the next step here?

**Comment by GuyAglionby** [comment]
Sorry for the delay here @nschneid. I will have some time in a couple of weeks to revisit this
