### ISSUE TITLE
Cambridge Core: Year: 0000

### ISSUE THREAD

**Issue by DaveJarvis** [zotero/translators#1944]
1. Start Zotero
1. Start Firefox
1. Install Zotero add-on for Firefox
1. Restart Firefox, if necessary
1. Visit https://www.cambridge.org/core/journals/geological-magazine/article/cyclostratigraphy-stratigraphic-gaps-and-the-duration-of-the-hettangian-stage-jurassic-insights-from-the-blue-lias-formation-of-southern-britain/7FBF2C9D5CB1286E5DE762419BD8101E
1. Click **Save to Zotero** icon in Firefox

**Expected Results**
The entry in Zotero has its year set to `2018`.

**Actual Results**
The year is set to `0000`.

**Screenshot**
![0000](https://user-images.githubusercontent.com/2131950/57487554-c3938880-7265-11e9-8643-de7c485341db.png)

**Comment by dstillman** [comment]
The Cambridge Core translator just uses Embedded Metadata from the site, which is providing the `undefined/ed` value:

```html
<meta name="citation_publication_date" content="undefined/ed">
```

The 0000 in the middle pane is just what happens if there's a value in the Date field that can't be parsed, and it might make more sense for that to be blank instead, but the problem is still the underlying data. You should report this to them.

**Comment by DaveJarvis** [comment]
> it might make more sense for that to be blank instead

Agreed, especially since `0000` is a valid year.
