### ISSUE TITLE
WorldCat: Constant fallback from WorldCat Discovery Service to Open WorldCat

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2066]
https://forums.zotero.org/discussion/80185/erreur-lors-delenregistrement-avec-worldcat

This seems to be happening pretty consistently on worldcat.org. I'm not sure of the difference between WDS and OW, but it'd be nice to avoid the error message.

**Comment by zuphilip** [comment]
Do you have an example URL for this? - I tested our test cases https://sbts.on.worldcat.org/oclc/667874424 and https://sbts.on.worldcat.org/oclc/795005226 which both seem to work okay for me.

**Comment by dstillman** [comment]
https://www.worldcat.org/title/test/oclc/870131528&referer=brief_results

**Comment by zuphilip** [comment]
Okay, for that URL I see the Open World Cat as the top translator which then also works fine. But I also see WorldCat Discovery Services as another translator (with the same priority 100) which will lead to an error. On such a page the WorldCat Discovery Service translator should not be available, because it is not working.

The problem occurs because the value of extracted database ID which is needed for creating the RIS URL is `null`:

https://github.com/zotero/translators/blob/bffebf9c2b65a1e731a596245cd11ae3cb21be6d/WorldCat%20Discovery%20Service.js#L87

Thus, we can simply test for the presence of an element with id `dbList` in the detectWeb as well, to avoid that this translator is offered, in cases when it is not working. But maybe @adam3smith has other ideas or experiences with this issue.

**Comment by dstillman** [comment]
Oh, yeah, I get WDS first. Since they're both 100, it's probably nondeterministic.

**Comment by adam3smith** [comment]
(I had never seen this before it was reported, so no other ideas, no; the proposed solution sounds good)
