### ISSUE TITLE
NASA ADS are incorrectly attached

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2111]
Reported: https://forums.zotero.org/discussion/80819/problem-in-downloading-bulk-papers-from-ads#latest

Sample URL: https://ui.adsabs.harvard.edu/search/q= abs:"open cluster" author:"bica" year:2012&amp;sort=date desc, bibcode desc&amp;p_=0  downloading all 6 papers leads to seemingly random assignment of PDFs to metadata

**Comment by GuyAglionby** [comment]
This is because the list of ids passed into `scrape` isn't necessarily in the same order as the items returned from the unAPI translator, so the `id` used to construct the pdf link ([this one](https://github.com/zotero/translators/blob/20bf8fd8e45e011b5900b2e5442c6f25af398bfe/NASA%20ADS.js#L103)) is not guaranteed to correspond to the `item`. Retrieving the id directly from the item instead (e.g. `let id = item.url.split('/').pop();`) looks like it fixes the issue.

If this isn't robust enough I think there'd be other ways of doing this, e.g. calling the API for each item individually rather than doing one call for all, if multiple requests would be acceptable. Happy to send a PR with whichever approach is most appropriate. 

One thing that doesn't seem quite right is the snapshotting -- for multiples it will snapshot the search page for each item, and for individual docs [line 86](https://github.com/zotero/translators/blob/20bf8fd8e45e011b5900b2e5442c6f25af398bfe/NASA%20ADS.js#L86) must be changed to `scrape([extractId(url)], doc);`. This can be changed altogether I think just by using the url from `item` (like is done [here](https://github.com/zotero/translators/blob/20bf8fd8e45e011b5900b2e5442c6f25af398bfe/Semantic%20Scholar.js#L96-L98)).

**Comment by dinilbose** [comment]
Any solution for this issue?
