### ISSUE TITLE
SAGE Journals detection problems

### ISSUE THREAD

**Issue by mtrojan-ub** [zotero/translators#2121]
success (/doi/.../): https://journals.sagepub.com/doi/full/10.1177/1057567719896160
problem (only /doi/): https://journals.sagepub.com/doi/10.1177/1057567719896160
Also problem (/toc/): https://journals.sagepub.com/toc/SCP/current

Seems like the target pattern needs to be fixed. There has been another detection fix a short time ago, see  #2077

Any help would be appreciated!

@placardo and @adam3smith, do you have any suggestions how to extend the target pattern without breaking it?

**Comment by placardo** [comment]
Originally I think that the target was only aimed at /full/ and /abs/ to avoid triggering the translator on pages showing a pdf. However [it appears](https://github.com/zotero/translators/pull/2077/files#r355216746) that the translator actually only need the doi in the URL to get the RIS data so I guess it would be safe to replace the different detection patterns by only /doi/ (this would take care of your second case).

For the third case this is my mistake in the previous fix, I changed the `div` line 57 into a `span` because it was what appeared in search results pages but I just realized that in toc pages the link is indeed wrapped into a `div`...

@adam3smith I can open a pull request for those two things if you think it's ok

**Comment by adam3smith** [comment]
> @adam3smith I can open a pull request for those two things if you think it's ok

Yes, that'd be great, thanks! Agree with your assessment on both of those.

**Comment by AbeJellinek** [comment]
Working fine now.
