### ISSUE TITLE
Nature Translator Broken

### ISSUE THREAD

**Issue by SR--** [zotero/translators#2126]
"An error occurred saving with .... Attempting to save using Embedded Metadata instead."

Trying this address: https://www.nature.com/articles/452919a

Forum discussion is at: https://forums.zotero.org/discussion/comment/349004#Comment_349004

**Comment by lgsmith** [comment]
I've been having this issue as well. I noticed it more than a month ago, based on the symptoms within my library (because it's grabbing nature blurbs for social media, not full abstracts, from nature articles it's been doing this to me since mid-January when I started reviewing nature for my group). 

I'm not sure how to help with this, but I'm modestly familiar with scientific computing and would be willing to take a whack at helping if someone had a suggestion for where to look, or any other pointers. I can't guarantee anything good will come of it but I'd be glad to contribute if I can.

**Comment by dstillman** [comment]
Assuming this was in Firefox, this should be fixed by https://github.com/zotero/zotero-connectors/commit/718237a6bcc354b27a2a8db474f5275407b529ff, available in the latest <a href="https://www.zotero.org/support/dev_builds#zotero_connector">Zotero Connector beta</a>. The fix will be included in Zotero Connector 5.0.67.
