### ISSUE TITLE
FAO Publications: Unnecessary 'other' for Language

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2177]
URL: http://www.fao.org/publications/card/en/c/5014f143-be17-4b58-b90e-f1c6bef344a0/

See https://github.com/zotero/translators/pull/2176/files#r425723082

@swifterslb, let us know if you'd be able to look into this.

**Comment by swifterslb** [comment]
OK I get it. The PDF URL ends with "E" not "e" so it's not recognized. I'll fix later. Will also add Italian since it's the most common one after the usual 6 languages.

Also, the language of the abstract webpage and the language of the publication itself are independent. The "en" in abstract webpage URL only designates the language of the webpage itself, not the language of the publication. For example, the URL has a French version: http://www.fao.org/publications/card/fr/c/5014f143-be17-4b58-b90e-f1c6bef344a0/ , but the PDF link is the same, because the file only has English version. The language of the abstract webpage can be switched by using the links at the top right corner and all the 6 languages are usually available.

Thanks so much for spotting this.

**Comment by swifterslb** [comment]
New pull request at https://github.com/zotero/translators/pull/2179
