### ISSUE TITLE
Import NCBI/Medline abstracts where newlines start with all caps letters

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2224]
Reported here: https://forums.zotero.org/discussion/83719/some-abstracts-from-pubmed-truncated#latest

Sample data here:
https://gist.github.com/michi-zuri/5750a395438492c6c32e30d667fa4174

**Comment by michi-zuri** [comment]
Interestingly, the title with a second line starting on `SAMD9` was not affected, while the abstract was truncated with this term. But when changing this name in the title to `AU - MD9` even the title gets truncated without warning, here is a minimal example where the title is truncated as well:

```
PMID- 000000000000
OWN - NLM
STAT- In-Process
LR  - 20200715
TI  - Outcomes of Hematopoietic Cell Transplantation in Patients with Germline
      AU - MD9/SAMD9L Mutations.
PG  - 2186-2196
LID - S1083-8791(19)30439-2 [pii]
LID - 10.1016/j.bbmt.2019.07.007 [doi]
AB  - Germline mutations in SAMD9 and SAMD9L genes cause MIRAGE... A patient with
      SAMD9L-associated MDS died of diffuse alveolar hemorrhage. 
FAU - Ahmed, Ibrahim A
AU  - Ahmed IA
```

**Comment by michi-zuri** [comment]
The `-` in the regex 
https://github.com/zotero/translators/blob/cc92035de47a8fbf41595514183c60b752c3831b/MEDLINEnbib.js#L181 
and the missing consideration of leading spaces for each line due to stripping them all here
https://github.com/zotero/translators/blob/cc92035de47a8fbf41595514183c60b752c3831b/MEDLINEnbib.js#L161
explain why `SAMD9L-associated` triggered the processing of the tag up to that point in the abstract, but not in the title. 

Another minimal exmample, this time only the title gets truncated:

```
PMID- 000000000000
OWN - NLM
STAT- In-Process
LR  - 20200715
TI  - Mickey Mouse had an 
      O-some day!
AB  - Mickey Mouse had a quiet day until something happened and
      SAMD9L was caught in the end. 
FAU - Mouse, Mickey
AU  - Mouse M 
```
