### ISSUE TITLE
Patent number missing from google patents when using translation-server only

### ISSUE THREAD

**Issue by mvolz** [zotero/translators#2230]
I.e. https://patents.google.com/patent/US3625104A/en does not include the patent number in the results.

It looks like it *should* (https://github.com/zotero/translators/blob/master/Google%20Patents.js#L191), maybe this is outdated.

**Comment by dstillman** [comment]
You're testing this in translation-server? Most of the data for that translator depends on JavaScript rendering and won't be saved in translation-server. This works in Zotero.

There are meta tags with some of the data that could potentially be used instead of scraping the rendered DOM, but I haven't looked through the commit history to see if those were considered or used previously. In the case of the patent number specifically, it has `<meta name="citation_patent_number" content="US:3625104">`, whereas the number shown on the page is `US3625104A`. Not sure about that discrepancy or what it implies for the other fields, but at least in that case we could also just get the full number (without the colon and with the "A") from the URL or `<link rel="canonical">`.
