### ISSUE TITLE
Kubikat (Aleph) Fails to Import

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#2255]
User reports this used to work and MARC is present on the page:
Reported: https://forums.zotero.org/discussion/85358/issue-with-translator-kubikat#latest
Example: https://forums.zotero.org/discussion/85358/issue-with-translator-kubikat#latest

**Comment by AbeJellinek** [comment]
The [link in the report](https://aleph2.mpg.de/F/F1DJKYR17ILJ2SQH6Q78PKPV415PTHYGKN2J5PICY4C89PRIRF-63687?func=full-set-set&set_number=002245&set_entry=000035&format=999) fails to import, but the issue seems to be that `detectWeb` should fail and `doWeb` should never run; it's the library's homepage, not an importable catalog record. Actual books ([example](https://aleph2.mpg.de/F/FXPBUPI4F7S5QN3M2TSEDBJM5I5INT86VG624HH3BT81E52PYM-05671?func=full-set-set&set_number=004725&set_entry=000002&format=999)) import fine. I'll see if there's a decent heuristic we can use to make sure `detectWeb` returns false on non-record pages.

**Comment by AbeJellinek** [comment]
(It's possible that the link died and it's showing me the homepage as a fallback, but I can't find an archived version of the page to verify that.)

**Comment by adam3smith** [comment]
Sorry, I meant to put a permalink there and just duplicated the link to the forum. I have other examples failing, e.g. https://aleph.mpg.de/F?func=direct&doc_number=000000037&local_base=mpg01 -- looks like something wrong with how the MARC is parsed in?

**Comment by AbeJellinek** [comment]
Oh, OK, I see. It looks like the MARC parser is doing the right thing, assuming that it's passed MARC. But that record is MAB! There's no obvious way to tell whether a record is MARC or MAB from the page, so I'll make it fall back on our MAB2 translator if MARC fails.
