### ISSUE TITLE
don't support capturing PDF links on Firefox

### ISSUE THREAD

**Issue by wwtan** [zotero/translators#2327]
Hi,

I have been referred here from [this issue of JabRef-Browser-Extension](https://github.com/JabRef/JabRef-Browser-Extension/issues/244). Namely, when capturing PDF links, the HTML response is captured instead of the PDF file. This is the example of [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3123451/).

I am using Firefox 84.0.2, JabRef 5.2, JabRef Browser extension 2.3.

**Comment by adam3smith** [comment]
Both the Pubmed Central PDF and the Sage paper you link in the issue at JabRef import with PDF and metadata in Zotero. Impossible to say what the issue is exactly for you, might be something specific to your set-up such as your university proxy or might be an issue with JabRef's implementation of Zotero code. 
If you want to troubleshoot this with Zotero, you'd need to test and replicate  with the Zotero Firefox add-on, then run through https://www.zotero.org/support/troubleshooting_translator_issues and post to forums.zotero.org
