### ISSUE TITLE
There is something wrong with OSA

### ISSUE THREAD

**Issue by JarmoHu** [zotero/translators#2360]
This is the article
_https://www.osapublishing.org/ol/fulltext.cfm?uri=ol-40-24-5750&id=333270_

this is the html metadata
```xml
<meta name="dc.title" content="Metamaterial-waveguide bends with effective bend radius &amp;lt;&amp;#x2009;&amp;#x3BB;&lt;sub&gt;0&lt;/sub&gt;/2">
```
this is zotero import from firefox connecter
```
Metamaterial-waveguide bends with effective bend radius &lt;&#x2009;&#x3BB;<sub>0</sub>/2
```

this is zotero import from PDF
```
Metamaterial-waveguide bends with effective bend radius < λ_0/2
```

**Comment by AbeJellinek** [comment]
I'm not sure we can do anything about this on our end. They're double-escaping the character entities in their metadata. That `meta` tag should be more like:

```html
<meta name="dc.title" content="Metamaterial-waveguide bends with effective bend radius &lt;&#x2009;&#x3BB;<sub>0</sub>/2">
```

As it is, Zotero is importing the title correctly based on the data it's given. (\<sub> is better than an underscore - it will appear as subscript text in citations, although it isn't rendered that way in the library.)

OSA is translated using Embedded Metadata. We can't just make that translator decode HTML entities twice, because that's usually wrong and could be dangerous. We can't add a special case for this site, because it's only one of the many, many thousands that Embedded Metadata scrapes. And it's not worth writing a separate translator for, because Embedded Metadata produces results for this site that are quite good - except, it seems, when it comes to oddly escaped characters.

Ideally, someone can reach out to OSA's web developer and ask them to fix their `meta` tags. It's probably making article links posted on Twitter, Facebook, etc., look just as funky.

**Comment by dstillman** [comment]
> It's probably making article links posted on Twitter, Facebook, etc., look just as funky.

(Or it would, if the whole site wasn't locked behind a CAPTCHA.)

**Comment by AbeJellinek** [comment]
Looking at it again, I guess there is an OSA translator! When I was playing with the page yesterday, I was only getting Embedded Metadata, because the OSA translator targets [`abstract.cfm`](https://www.osapublishing.org/ol/abstract.cfm?uri=ol-40-24-5750) but not [`viewmedia.cfm`](https://www.osapublishing.org/ol/viewmedia.cfm?uri=ol-40-24-5750&html=true), which @JarmoHu linked to. They're just different views on the same item.

On the one hand, the OSA translator isn't really doing anything for us. It just deals with multiples and calls EM. On the other hand, we _do_ already have it, so it might be worth adding a hack to make titles translate correctly until the site administrators fix the issue on their end.

@dstillman, what do you think?

**Comment by dstillman** [comment]
Sure, we might as well fix it in the translator. We certainly have plenty of translators that clean up EM.

(I think having translators that just handle multiples and call another translator is also fine.)
