### ISSUE TITLE
Wikipedia - PDF Download

### ISSUE THREAD

**Issue by errotu** [zotero/translators#2773]
It would be great if a PDF download could be added to the Wikipedia translator. Wikipedia publishes PDFs of its articles via [its REST-API](https://en.wikipedia.org/api/rest_v1/#/Page%20content/get_page_pdf__title_):

> api/rest_v1/page/pdf/{title}

So, as an example, the PDF for 

> https://en.wikipedia.org/wiki/Net_neutrality_in_the_United_States 

can be found on:

> https://en.wikipedia.org/api/rest_v1/page/pdf/Net_neutrality_in_the_United_States

Thanks a lot for your support and great work!

**Comment by dstillman** [comment]
Please [post feature requests to the Zotero Forums](https://github.com/zotero/translators/blob/master/.github/ISSUE_TEMPLATE.MD).

Zotero saves a snapshot of the page with full content, so we wouldn't add this by default. The PDF also appears to be generated on demand and takes a while to download, and presumably is load-intensive on their end, so I don't think it's particularly appropriate to do this by default. We've explained in the forums why we don't consider PDFs to be an appropriate snapshot format for web content:

https://forums.zotero.org/discussion/comment/380407/#Comment_380407
https://forums.zotero.org/discussion/comment/380282/#Comment_380282

It's a little different in this case because Wikipedia has access to the raw content, but PDF still isn't the primary output format and there can be unexpected formatting problems (e.g., tables running off the page).

If you really want this, you could create a copy of the Wikipedia translator with a different id that has a higher priority and that saves the PDF instead, or you can simply click through to the PDF and drag the fav icon onto the new item in Zotero to add it as an attachment. A future version of the Zotero Connector will likely make it possible to attach the PDF to the selected item in Zotero via a context menu.

**Comment by errotu** [comment]
Thank you very much for the quick feedback and tips! I will take a look into it and maybe try to modify the Wikipedia translator accordingly on my own. 

Generally, I would suggest to implement an option to download websites (additionally) as PDF. This does not only allow easy annotation on desktop computers (HTML annotation tools are not very common) but gives me in particular the option to read the content on my eInk-Tablet which only supports PDF. After all, I generally don't save webpages for the layout but for the (written) content. But I read the posts you provided links for and see that you have a different stance on this issue.

Just a quick note regarding Github/Zotero Forums: I actually read the issue template and felt like this line applied to me. Did I understand it wrong?

> If you’re sure your issue relates to a specific Zotero translator, you’re welcome to create an issue here.

**Comment by dstillman** [comment]
> Just a quick note regarding Github/Zotero Forums: I actually read the issue template and felt like this line applied to me. Did I understand it wrong?

Sorry, my fault — I've updated that to clarify that it's specific to translator bug reports. For something like this, we'd still prefer it go to the forums to keep the discussion open to the widest audience.
