### ISSUE TITLE
BibLaTeX export: Strip unbalanced braces in `file`

### ISSUE THREAD

**Issue by dstillman** [zotero/translators#2796]
https://forums.zotero.org/discussion/94868/potential-biblatex-export-bug

Sounds like it's either the rare broken attachment with `{` in the filename or a broken BibTeX file.

(Unless there's an easy way to further clean filenames that we copy into an export directory based on the translator in question. I didn't check to see whether that's the case, but if not I don't think we need to put too much effort into making this possible.)

**Comment by AbeJellinek** [comment]
We actually already have [a fix for this](https://github.com/zotero/translators/blob/master/BibTeX.js#L1535-L1546) in the BibTeX translator. Not sure why it hasn't made it into BibLaTeX yet. Because `attachment.saveFile` lets the translator provide a path, the only situation in which the `file` in the BibTeX will end up mismatched with the path of the actual file is when "Export Files" is unchecked (and I'm not sure it really matters in that case).

**Comment by dstillman** [comment]
Ah, great.
