### ISSUE TITLE
DOI Translation issue: ReferenceError: requestText is not defined

### ISSUE THREAD

**Issue by stefan-sigle** [zotero/translators#3252]
As described in https://github.com/zotero/translation-server/issues/163 we are running into trouble translating DOIs but not other identifiers such as PMIDs.

Maybe some of the translators are unavailable or out of date?
Any hints are appreciated.

**Comment by aborel** [comment]
Your test apparently doesn't recognize the requestText() function in `DOI Content Negotiation.js`, which is strange because it's a standard function in translators (recommended over older idioms to retrieve third-party content). That particular translator has been updated to use requestText() 5 months ago https://github.com/zotero/translators/commit/7711e87f07452db5dbce144a610d8a3717756263 and hasn't changed since then. Did something else change in the translation-server code?

**Comment by dstillman** [comment]
https://github.com/zotero/translation-server/issues/163#issuecomment-1943532382
