### ISSUE TITLE
Allow linked files instead of attachments on import

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#681]
This is becoming an increasingly frequent request. I haven't looked at the details, but I assume the coding part is fairly trivial, so the main question is how to implement this. The three obvious choices are 1) Pref 2) Hidden pref 3) prompt on import

@dstillman - I figured this would be more focused here, but if you prefer for it to stay on the forums feel free to close here and I'll start a thread.

**Comment by timflutre** [comment]
Hello,
I am trying to switch from CiteULike to Zotero. I even wrote myself a [script](https://github.com/timflutre/quantgen/blob/master/citeulike2others.py) in Python to help in that move. I just found this issue on GitHub because I am stuck with this question of linked files. All my files already are in a directory on my computer and I would prefer not to move them. In a given bib entry in the file exported from citeulike, I have a field such as: file = "{article.pdf:application/pdf}". I know how to code a bit, but can't figure out how to implement support for linked files at import. Would you have any advice?

**Comment by laclaro** [comment]
please add this feature. Especially on a shared network drive (portable) this speeds up zotero!

**Comment by dstillman** [comment]
This was implemented in March 2019.
