### ISSUE TITLE
IACR eprint translator broken

### ISSUE THREAD

**Issue by dfc** [zotero/translators#703]
The IACR translator is not working:

https://eprint.iacr.org/2014/218

**Comment by FredericJacobs** [comment]
I believe this has not been properly fixed. Even though the translator is available, on clicking it, it attempts to retrieve the page over HTTP. Chrome doesn't allow HTTP AJAX requests within a page loaded over HTTPS, resulting in the following warnings.

![screen shot 2015-05-21 at 16 37 09](https://cloud.githubusercontent.com/assets/400296/7750979/a72a0520-ffd7-11e4-865d-6dd5f8ff9b79.png)

I think this can be fixed by using [relative protocol URLs](http://billpatrianakos.me/blog/2013/04/18/protocol-relative-urls/).

**Comment by adam3smith** [comment]
right -- that request is the attachment download, which still has the old hardcoded URL. Should be a quick fix if someone wants to take it, it'll take me a little time otherwise.
