### ISSUE TITLE
Add support for new NDL Catalog

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#927]
http://iss.ndl.go.jp/
I don't think this is a format we know -- has JSON and RDF, so should be reasonably easy, though I'm not recognizing these as standards.
requested: https://forums.zotero.org/discussion/20128/ndl-import/#Item_11

**Comment by zuphilip** [comment]
The JSON data would be easy to grab, however their not following any metadata schema there that I am aware of. Thus, I suggest to concentrate on the RDF data. 

An example for their RDF data: http://iss.ndl.go.jp/books/R100000039-I001424605-00.rdf

The DublinCore fields should import already with the RDF translator. However, the properties from the `dcndl` namespace are more tricky because that is their own vocabulary. I suggest to determine somehow the itemType and whatever we can receive from the DC fields.

**Comment by adam3smith** [comment]
yeah, the itemType is the problem -- I'd simply DOMParse it and grab it from their materialType field. That seems a lot more stable than any DC-based guesswork. Slightly less efficient, but efficiency in ```doWeb``` is secondary.

**Comment by zuphilip** [comment]
And here is a list of all itemTypes in their vocabulary: http://ndl.go.jp/ndltype/ = http://www.ndl.go.jp/jp/aboutus/standards/meta/2011/12/ndl-type.rdf . Now, we just have to put everything together and work out the details :wink:

**Comment by adam3smith** [comment]
I make the typeMap, you write the translator?

**Comment by zuphilip** [comment]
That sounds like a plan. However, I cannot do it super soon.

**Comment by adam3smith** [comment]
OK, Typemap as a google spreadsheet here:
https://docs.google.com/spreadsheets/d/1d3jfcRUJl665aRZpokdkqeIWeQeaZJGeKnp08Z2vcIE/edit?usp=sharing
I figured turning this into a JS object was easy enough, didn't know which of the fields you'd end up using.
