### ISSUE TITLE
[EM] add support for additional OpenGraph formats

### ISSUE THREAD

**Issue by adam3smith** [zotero/translators#932]
http://ogp.me/
haven't checked in detail what we currently recognize, but we'd want to support ```article:```, ```book:```, ```video:```, and ```music:```

**Comment by adam3smith** [comment]
E.g. this has some of the ```article:``` tags: https://hbr.org/2015/08/how-to-do-walking-meetings-right

**Comment by adam3smith** [comment]
Also add the simple meta name="author": http://www.w3schools.com/tags/att_meta_name.asp

**Comment by zuphilip** [comment]
In the PR #973 there are also examples with `og` as well as `<meta name="author" content="..."/>`.

**Comment by adam3smith** [comment]
closed in https://github.com/zotero/translators/pull/998

**Comment by owcz** [comment]
Not OG but for EM, I think the following should be supported:

 1. `<span itemprop="name" content="Andrew Goldfarb">` ([ex](http://www.ign.com/articles/2012/07/27/limbo-follow-up-project-2-is-at-least-2-years-away)) for author ([spec](https://www.w3.org/TR/2009/WD-html5-20090825/microdata.html))
 2. `<meta name="live_date" value="2012-07-27">` ([ex](http://www.ign.com/articles/2012/07/27/limbo-follow-up-project-2-is-at-least-2-years-away)) for date
 - (then the _IGN_ translator can be deprecated)
 - `<meta name="pub_date" content="2015-12-21T20:15:19+00:00">` ([ex](http://www.pcgamer.com/2015-personal-pick-cibele/)) for date
 -  `<time class="meta__time updated" datetime="2014-08-04T18:00:00-04:00">` ([ex](http://kotaku.com/shes-making-an-honest-game-about-sex-1615923190)) for date
 - Should [_Wired_](http://www.wired.com/2015/05/sex-videogames-make-feel-weird-thats-point/) be using `<meta itemprop="datePublished" content="2015-05-25T05:45:37+00:00">` or `<meta name="DisplayDate" content="2015-05-25">` instead of what it's using right now?
 - [_Eurogamer_](http://www.eurogamer.net/articles/2015-11-02-cibele-review) would use `<span itemprop="datePublished" content="2015-11-05">` too (many of these sites still need custom author support—I'll work on that)
 - [_USgamer_](http://www.usgamer.net/articles/gone-home-console-edition-ps4-review) supports `<p class="published" itemprop="datePublished" content="2016-16-01">`, but do we support that date format? (YYYY-DD-MM not MM-DD)
 - EM didn't use `<meta property="og:author" content="Jonathan Holmes">` for author with _[Destructoid](http://www.destructoid.com/cibele-is-a-game-about-love-sex-and-the-internet-288412.phtml)_
 - JSON-LD, such as `"name": "Jake Muncy"` in _[A.V. Club](http://www.avclub.com/review/cibele-showcases-expressive-power-autobiographical-227929)_
 - Disqus comments sections also hold some date-created metadata, but I think it might be a better route to just have sites implement real metadata

**Comment by zuphilip** [comment]
See also ticket for microdata #366, for JSON-LD #917

**Comment by adam3smith** [comment]
OK on 2,4. Will look 9. 
10 definitely, likely in a separate translator that can then be called from EM (and should as a final goal also enable export I think) as per the ticket @zuphilip links to.

6 uses the date in the parsley JSON
```
<meta name='parsely-page' content='{"title": "If Sex Videogames Make You Feel Weird, That&#8217;s the Point", "link": "http://www.wired.com/2015/05/sex-videogames-make-feel-weird-thats-point/", "image_url": "http://www.wired.com/wp-content/uploads/2015/05/Screen-Shot-2015-05-21-at-12.32.53-PM-150x150-e1432241140212.png", "type": "post", "post_id": "1784713", "pub_date": "2015-05-25T05:45:37+00:00", "section": "WIRED", "author": "Wired Staff", "tags": []}'>
```

which makes sense to me

1,5,7,8: generally speaking no. The problem is that these will often end up being used mulitple times on a page, e.g. under a link+description for another article or even a comment.

What we _could_ do is to add 1.) to the byline search and add a date search that follows the same logic (find the element closest to the title). If so, like the currently byline search, that should be a last "desparate" attempt if all else fails, given chance of getting something wrong.

Let us know if you're interested in taking any of these.

**Comment by zuphilip** [comment]
Microdata are nested, i.e. 1 looks like
```
<... itemscope itemtype="http://schema.org/Article">
   <... itemprop="articleBody">
      <... itemprop="author" itemscope itemtype="http://schema.org/Person">
         <... itemprop="name" content="Andrew Goldfarb">
```
