### ISSUE TITLE
Incorrect parameter name "name" in creator object?

### ISSUE THREAD

**Issue by mvolz** [zotero/translators#983]
From http://jama.jamanetwork.com/article.aspx?articleid=203344 I get the creators array

```
"creators":[{"name":"Detsky ME","creatorType":"author"},{"name":"McDonald DR","creatorType":"author"},{"name":"Baerlocher MO","creatorType":"author"},{"name":"Tomlinson GA","creatorType":"author"},{"name":"McCrory DC","creatorType":"author"},{"name":"Booth CM","creatorType":"author"}],
```
I've only ever seen firstName and lastName- is "name" a valid parameter?

**Comment by kaldari** [comment]
It looks like "name" is mentioned at https://www.zotero.org/support/dev/web_api/v3/types_and_fields. 

Interestingly, the same article queried via crossref.org's API gives the full author information.

**Comment by adam3smith** [comment]
yeah, `name` is used in the API JSON instead of `lastName` with `fieldMode=1` (which is what the translator returns locally). I don't have any background on the rational for the difference, though. It's unfortunate that JAMA puts such crappy data into their RIS, but there isn't much we can do about it I'm afraid.

**Comment by mvolz** [comment]
CrossRef has pretty good data for JAMA- could the translator be augmented
with that using the crossref translator?
